fruitipediaapp/profiles/urls.py
from django.urls import path

from fruitipediaapp.profiles.views import create_profile, edit_profile, delete_profile, details_profile

urlpatterns = [
    path('create/', create_profile, name='create profile'),
    path('edit/', edit_profile, name='edit profile'),
    path('delete/', delete_profile, name='delete profile'),
    path('details/', details_profile, name='details profile'),
]

fruitipediaapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('fruitipediaapp.common.urls')),
    path('profile/', include('fruitipediaapp.profiles.urls')),
    path('fruit', include('fruitipediaapp.fruits.urls')),
]

fruitipediaapp/fruits/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from fruitipediaapp.fruits import validators
from fruitipediaapp.profiles.models import Profile


# Create your models here.
class Fruit(models.Model):
    MAX_NAME_LENGTH = 30
    MIN_NAME_LENGTH = 2

    name = models.CharField(
        unique=True,
        max_length=MAX_NAME_LENGTH,
        validators=[
            MinLengthValidator(limit_value=MIN_NAME_LENGTH),
            validators.all_letters_validator,
        ],
        error_messages={
            'unique': 'This fruit name is already in use! Try a new one.'
        },
    )

    image_url = models.URLField()

    description = models.TextField()

    nutrition = models.TextField()

    owner = models.ForeignKey(
        to=Profile,
        on_delete=models.CASCADE
    )

fruitipediaapp/profiles/models.py
from django.conf import settings
from django.core.validators import MinLengthValidator
from django.db import models

from fruitipediaapp.profiles import validators


# Create your models here.
class Profile(models.Model):
    MAX_FIRST_NAME_LENGTH = 25
    MIN_FIRST_NAME_LENGTH = 2
    MAX_LAST_NAME_LENGTH = 30
    MIN_LAST_NAME_LENGTH = 1
    MAX_EMAIL_LENGTH = 40
    MAX_PASSWORD_LENGTH = 20
    MIN_PASSWORD_LENGTH = 8

    first_name = models.CharField(
        max_length=MAX_FIRST_NAME_LENGTH,
        validators=[
            MinLengthValidator(limit_value=MIN_FIRST_NAME_LENGTH),
            validators.first_letter_validator,
        ],
    )

    last_name = models.CharField(
        max_length=MAX_LAST_NAME_LENGTH,
        validators=[
            MinLengthValidator(limit_value=MIN_LAST_NAME_LENGTH),
            validators.first_letter_validator,
        ]
    )

    email = models.EmailField(
        unique=True,
        max_length=MAX_EMAIL_LENGTH,
    )

    password = models.CharField(
        max_length=MAX_PASSWORD_LENGTH,
        help_text="*Password length requirements: 8 to 20 characters",
        validators=[
            MinLengthValidator(limit_value=MIN_PASSWORD_LENGTH)
        ]
    )

    image_url = models.URLField(blank=True, null=True)

    age = models.PositiveSmallIntegerField(default=18, blank=True, null=True)

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

fruitipediaapp/profiles/forms.py
from django import forms

from fruitipediaapp.profiles.models import Profile


class BaseProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"


class CreateProfileForm(BaseProfileForm):
    class Meta(BaseProfileForm.Meta):
        fields = [
            'first_name',
            'last_name',
            'email',
            'password']

        labels = {
            'first_name': False,
            'last_name': False,
            'email': False,
            'password': False
        }

        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'}),
            'password': forms.PasswordInput(attrs={'placeholder': 'Password'})
        }


class EditProfileForm(BaseProfileForm):
    class Meta(BaseProfileForm.Meta):
        fields = [
            'first_name',
            'last_name',
            'image_url',
            'age'
        ]

        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'image_url': 'Image URL',
            'age': 'Age',
        }

fruitipediaapp/profiles/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from fruitipediaapp.profiles.forms import CreateProfileForm, EditProfileForm
from fruitipediaapp.profiles.models import Profile


# Create your views here.
def create_profile(request):
    create_profile_form = CreateProfileForm(request.POST or None)

    if request.method == 'POST':
        if create_profile_form.is_valid():
            user = User.objects.create_user(
                username=request.POST['first_name'],
                first_name=request.POST['first_name'],
                last_name=request.POST['last_name'],
                email=request.POST['email'],
                password=request.POST['password'],
            )
            profile = create_profile_form.save(commit=False)
            profile.user = user
            profile.save()

            # auto login upon signup
            login(request, user)

            return redirect('dashboard')

    context = {
        'create_profile_form': create_profile_form
    }
    return render(request, 'profiles/create-profile.html', context)


def edit_profile(request):
    profile = Profile.objects.get(email=request.user.email)
    edit_profile_form = EditProfileForm(request.POST or None, instance=profile)

    if request.method == 'POST':
        if edit_profile_form.is_valid():
            edit_profile_form.save()
            return redirect('dashboard')

    context = {
        'edit_profile_form': edit_profile_form
    }
    return render(request, 'profiles/edit-profile.html', context)


def delete_profile(request):
    profile = Profile.objects.get(email=request.user.email)

    if request.method == 'POST':
        request.user.delete()
        profile.delete()
        logout(request)
        return redirect('index')

    context = {}
    return render(request, 'profiles/delete-profile.html', context)


def details_profile(request):
    profile = Profile.objects.get(email=request.user.email)

    context = {
        'profile': profile
    }
    return render(request, 'profiles/details-profile.html', context)

templates/profiles/create-profile.html
{% extends 'base.html' %}

{% block main_content %}
    <!-- Create Profile Form -->
    <section id="register">
        <div class="form">
            <h2>Create Profile</h2>
            <form class="register-form" action="{% url 'create profile' %}" method="post">

                {{ create_profile_form }}

                <button type="submit">Create</button>

                {% csrf_token %}
            </form>

        </div>
    </section>
{% endblock %}

templates/profiles/delete-profile.html
{% extends 'base.html' %}

{% block main_content %}
    <section id="edit">

        <div class="form">
            <h1>Are you sure you want to delete your profile?</h1>

            <!-- Delete Profile Form -->
            <form id='delete' class="register-form" action="{% url 'delete profile' %}" method="post">
                <!-- Confirm Button -->
                <button type="submit">Yes</button>
                
                {% csrf_token %}
            </form>
            <!-- End Delete Profile Form -->
        </div>

    </section>
{% endblock %}

templates/profiles/details-profile.html
{% extends 'base.html' %}
{% load static %}

{% block main_content %}

    <!-- Profile Details Section -->

    <section id="details">
        <div id="details-wrapper">
            <h2>Profile Details</h2>

            {% if profile.image_url %}
                <!-- if the user has a profile image -->
                <img id="details-img" src="{{ profile.image_url }}"
                     alt="profile img"/>
            {% else %}
                <!-- if the user has NO profile image -->
                <img id="details-img" src="{% static 'images/default.jpg' %}" alt="profile img"/>
            {% endif %}
            <!-- user's full name -->
            <p id="details-title">{{ profile.first_name }} {{ profile.last_name }}</p>

            <div id="info-wrapper">
                <div id="details-description">
                    <!-- email -->
                    <p>
                        {{ profile.email }}
                    </p>
                    <!-- age -->
                    <p>
                        Age: {{ profile.age }}
                    </p>
                    <!-- number of posts -->
                    <p id="nutrition">Posts: {{ profile.fruit_set.all.count }}</p>

                </div>

                <!--Edit and Delete buttons -->
                <div id="action-buttons">
                    <a href="{% url 'edit profile' %}" id="edit-btn">Edit</a>
                    <a href="{% url 'delete profile' %}" id="delete-btn">Delete</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/profiles/edit-profile.html
{% extends 'base.html' %}

{% block main_content %}
    <!-- Edit Profile Form -->

    <section id="register">
        <div class="form">
            <h2>Edit Profile</h2>
            <form class="register-form" action="{% url 'edit profile' %}" method="post">


                {{ edit_profile_form }}

                <button type="submit">Edit</button>

                {% csrf_token %}
            </form>

        </div>
    </section>
{% endblock %}